
CREATE TABLE DEPARTMENT(
DID INT PRIMARY KEY,
NAME VARCHAR(100),
DESCRIPTION varchar(100),
BUDGET INT
)


CREATE TABLE CUSTOMER(
CID INT PRIMARY KEY,
LAST_NAME VARCHAR(100),
FIRST_NAME VARCHAR(100),
DID INT FOREIGN KEY REFERENCES DEPARTMENT(DID)
)

CREATE TABLE ORDER_(
OID INT PRIMARY KEY,
DESCRIPTION VARCHAR(100),
PRICE INT,
CID INT FOREIGN KEY REFERENCES CUSTOMER(CID)
)

CREATE TABLE SUPPLIER(
SID INT PRIMARY KEY,
TYPE VARCHAR(100),
DID INT FOREIGN KEY REFERENCES DEPARTMENT(DID)
)

CREATE TABLE FACTORY(
FID INT PRIMARY KEY,
TYPE VARCHAR(100),
LOCATION VARCHAR(100),
DID INT FOREIGN KEY REFERENCES DEPARTMENT(DID)
)

CREATE TABLE UTILITY_MACHINE(
UMID INT PRIMARY KEY,
TYPE VARCHAR(100),
DESCRIPTION VARCHAR(100),
FID INT FOREIGN KEY REFERENCES FACTORY(FID)
)

CREATE TABLE WAREHOUSE(
WID INT PRIMARY KEY,
LOCATION VARCHAR(100),
NAME VARCHAR(100),
FID INT FOREIGN KEY REFERENCES FACTORY(FID)
)

CREATE TABLE PRODUCT(
PID INT PRIMARY KEY,
TYPE VARCHAR(100),
DESCRIPTION VARCHAR(100),
PRICE INT,
NAME VARCHAR(100)
)

CREATE TABLE INVENTORY(
WID INT FOREIGN KEY REFERENCES WAREHOUSE(WID),
PID INT FOREIGN KEY REFERENCES PRODUCT(PID),
PRIMARY KEY(WID, PID),
QUANTITY INT
)

CREATE TABLE EMPLOYEE(
EID INT PRIMARY KEY,
LAST_NAME VARCHAR(100),
FIRST_NAME VARCHAR(100),
DOB DATE,
ADDRESS varchar(100),
SALARY INT
)

CREATE TABLE WORK_AT(
DID INT FOREIGN KEY REFERENCES DEPARTMENT(DID),
EID INT FOREIGN KEY REFERENCES EMPLOYEE(EID),
PRIMARY KEY (DID, EID),
EMPLOYNMENT_DATE DATE,
)

select * FROM EMPLOYEE
select * from ORDER_
select * from CUSTOMER
DROP TABLE UTILITY_MACHINE, INVENTORY, PRODUCT, WAREHOUSE, FACTORY, SUPPLIER, ORDER_, CUSTOMER, WORK_AT, EMPLOYEE, DEPARTMENT
